# Script to read and calculate the average error in a directory tree containing the
# trees generated by Cross-Validation.

def gettingAverageError():
	path = '/home/hialo/UnB/TCC2/codes/results/generated_trees/'
	total = 0
	NUMBER_OF_CASES = 10; 
	LINE = 10; # linha do arquivo aonde o percentual de erro dos testes se encontra

	for first_index in range (0, NUMBER_OF_CASES):
		var = 0
		for second_index in range (0, NUMBER_OF_CASES):
			full_path = path + str(first_index) + '/10/' + str(second_index) + '/matrix.txt'

			f = open(full_path)
			lines = f.readlines()
			lines[LINE] = lines[LINE].split(": ")[1]

			lines[LINE] = lines[LINE].split("%")[0]
			var += float(lines[LINE])

			f.close()

		total += var

	print total/NUMBER_OF_CASES*NUMBER_OF_CASES	

gettingAverageError()
